/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualsensor;

import java.io.*;
import javax.imageio.IIOException;

/**
 *
 * @author cody
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        oxigenSlider.setMaximum(255);
        oxigenSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderUpdate(evt);
            }
        });

        oxigenLabel.setText("Oxigen sensor");

        oxigenValue.setText("50");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(oxigenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(oxigenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oxigenValue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oxigenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oxigenValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oxigenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to update data to oxigen port when Oxigen sensor value is changed
     *
     * @param evt
     */
    private void sliderUpdate(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderUpdate
        oxigenValue.setText(Integer.toString(oxigenSlider.getValue()));
        writeToPort(oxigenSlider.getValue(), OXIGEN_SENSOR_PORT);
    }//GEN-LAST:event_sliderUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JLabel oxigenLabel = new javax.swing.JLabel();
    private static final javax.swing.JSlider oxigenSlider = new javax.swing.JSlider();
    private static final javax.swing.JLabel oxigenValue = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    final int OXIGEN_SENSOR_PORT = 2;
    final int NOISE_SENSOR_PORT = 3;
    final int DUST_SENSOR_PORT = 4;

    protected String filePath = "E:\\emu8086.io";
    protected RandomAccessFile fileHandler;

    /**
     * Initialize file to write data for emu8086 input ports
     */
    protected void initFile() {
        try {
            File fileToWrite = new File(this.filePath);
            this.fileHandler = new RandomAccessFile(fileToWrite, "rw");
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Method to write data to a specific port, data should be in range of 0 255
     *
     * @param data
     * @param port
     */
    public void writeToPort(int data, int port) {
        initFile();
        try {
            this.fileHandler.seek(port);
            this.fileHandler.write(data);
            closeFile();
        } catch (IOException e) {
            System.out.println(e.getMessage());
            closeFile();
        }
    }

    protected void closeFile() {
        try {
            this.fileHandler.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

}
